# Generated by Django 3.2.13 on 2022-07-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInformationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employeename', models.CharField(max_length=200)),
                ('Shift', models.CharField(max_length=200)),
            ],
        ),
    ]
