# Generated by Django 3.2.13 on 2022-07-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleshiftapp', '0002_employeeshiftinformationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinformationmodel',
            name='Date',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
