# Generated by Django 3.2.13 on 2022-07-11 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleshiftapp', '0003_employeeinformationmodel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeinformationmodel',
            name='Date',
        ),
    ]
