# Generated by Django 3.2.13 on 2022-07-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleshiftapp', '0004_remove_employeeinformationmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinformationmodel',
            name='Date',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
