# Generated by Django 3.2.13 on 2022-07-11 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleshiftapp', '0005_employeeinformationmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinformationmodel',
            name='Date',
            field=models.CharField(max_length=200),
        ),
    ]
